name = "vocab-app"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next"

[assets]
not_found_handling = "none"

[[d1_databases]]
binding = "DB"
database_name = "vocab-app-db"
database_id = "12fd5fec-39ad-4cf8-86cf-0df736b2179a"
