# Cloudflare Pages 配置
name = "vocab-app"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "vocab-app-db"
database_id = "12fd5fec-39ad-4cf8-86cf-0df736b2179a"
